#default project info followed by actual injected pom-specified values.
project:
  name: cart
  version: 1.0
  description: Cart MicroServices using Spring Boot
  artifact: com.msn.poc.cart
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

management:
  security:
    enabled: false
    
#security:
  #basic:
    #enabled: false
 