server:
  port: 8888

spring: 
  #profiles: 
    #active: native
  cloud:
    config:
      server:
        #native: 
          #searchLocations: file:///C:/Users/148367/Documents/GitHub/shoppingcart/config
        git: 
          uri: https://github.com/shamsnezami/shoppingcart/
          searchPaths: config 
          #username: shamsnezami
          #password: shams786
    
